[build]
  command = "yarn build"
  functions = "functions"
  publish = "build"
[[headers]]
  for = "/index.html"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding"
      Access-Control-Allow-Methods = "POST, GET, DELETE, PUT, OPTIONS"
[[headers]]
  for = "/manifest.json"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding"
      Access-Control-Allow-Methods = "POST, GET, DELETE, PUT, OPTIONS"
